a2lix_translation_form:
    locales:    %sylius.locales%
    templating: "A2lixTranslationFormBundle::default.html.twig"

a2lix_i18n_doctrine:
    manager_registry: doctrine

sylius_product:
    driver: doctrine/orm
    classes:
        product:
            model: Sylius\Candibambu\ProductBundle\Entity\Product
            form: Sylius\Candibambu\ProductBundle\Form\Type\ProductType
            repository: Sylius\Candibambu\ProductBundle\Doctrine\ORM\Product
